// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf4fH4bsSsg52J5a922nizySSn10Hl6qQ',
    appId: '1:173761637273:web:c990be49b7b7e48614c108',
    messagingSenderId: '173761637273',
    projectId: 'unimatchtest',
    authDomain: 'unimatchtest.firebaseapp.com',
    storageBucket: 'unimatchtest.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1JMAmA-kWE99_jYAkJiGvuRrKdhvMGKY',
    appId: '1:173761637273:android:657b26b9569b25f814c108',
    messagingSenderId: '173761637273',
    projectId: 'unimatchtest',
    storageBucket: 'unimatchtest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoufuTv_65DPM3EwdG_pJFoBvGisKF5_w',
    appId: '1:173761637273:ios:e30fd954b6a1e01f14c108',
    messagingSenderId: '173761637273',
    projectId: 'unimatchtest',
    storageBucket: 'unimatchtest.firebasestorage.app',
    iosBundleId: 'com.gcc.unimatch.unimatchGcc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoufuTv_65DPM3EwdG_pJFoBvGisKF5_w',
    appId: '1:173761637273:ios:e30fd954b6a1e01f14c108',
    messagingSenderId: '173761637273',
    projectId: 'unimatchtest',
    storageBucket: 'unimatchtest.firebasestorage.app',
    iosBundleId: 'com.gcc.unimatch.unimatchGcc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf4fH4bsSsg52J5a922nizySSn10Hl6qQ',
    appId: '1:173761637273:web:1b5d2bdd1b71923614c108',
    messagingSenderId: '173761637273',
    projectId: 'unimatchtest',
    authDomain: 'unimatchtest.firebaseapp.com',
    storageBucket: 'unimatchtest.firebasestorage.app',
  );
}
